### PR TITLE
56 add maxvit blocks for interior of model

### LINKED ISSUE #56: Add MaxViT blocks for interior of model
For reference:
- [The original paper](https://arxiv.org/abs/2204.01697)
- [Official TF implementation](https://github.com/google-research/maxvit)
- [Unofficial Torch implementation](https://github.com/ChristophReich1996/MaxViT)
- [timm implementation](https://github.com/huggingface/pytorch-image-models/blob/main/timm/models/maxxvit.py)

From the paper:
- All convolutions have kernels of size (3, 3) and are not dilated.
- normalized keys and queries are used
- All attention windows have size 8 by 8
- 32 attention heads
- skip connections from the output of each MaxVit block to the output of MaxVit. More precisely, the final output of MaxVit is a linear transformation of the outputs after each sub-block (after summing with the residual branch)
- MBConv in MaxVit uses the expansion rate of 4
- squeeze-and-excitation in the MBConv have bottleneck ratio of 0.25.
- pre-activation layer normalization throughout the network. 
- layer normalization after each convolution which is not the last convolution in the given sub-block.
- GELU inside MBConv (in MaxVit) and ReLu in all other places.
- stochastic depth in MaxVit with the probability of dropping a given sub-module (i.e. MBConv, local attention or gridded attention) increasing linearly thorough the network from 0 to 0.2. 

Tasks:
- [x] Add MBConv Layers
   - [x] Add skeleton code
   - [x] Add downsampling support
- [x] Add Grid Attention  Layers
- [x] Add Block Attention Layers 
- [x] Make metnet3 specific modifications
- [x] Add documentation
- [x] Test the dims and shapes
- [x] Figure out how to handle the configs

### PR DESCRIPTION
**Pull request by Raahul-Singh**
# Pull Request

## Description
Adds MaxVit Block, and it's subblocks for Metnet 3

Fixes #56

## How Has This Been Tested?

Added new shape tests for each new subblock

## Checklist:

- [x] My code follows [OCF's coding style guidelines](https://github.com/openclimatefix/.github/blob/main/coding_style.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by Raahul-Singh** [comment]
I've tested the code and added TODOs wherever I feel more scrutiny is required.

**Review by jacobbieker — APPROVED** [review]
This looks great! Thanks for all this work.

**Comment by Raahul-Singh** [comment]
Thanks @jacobbieker !

**Comment by rahul-maurya11b** [comment]
@jacobbieker sir, where can I make changes to fix issue #58  ?

**Pull request merged**
